env:
  node: true
  es2020: true

extends:
  - 'airbnb-base'

parserOptions:
  ecmaVersion: 11
  sourceType: module

plugins:
  - import

rules:
  no-console: 0
  no-unused-vars: 1
  import/order:
    - error
    - alphabetize:
        order: 'asc'
  import/extensions: 0 
  no-await-in-loop: 0
