env:
  node: true
  es2021: true
extends: airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  semi: [error, never]
  'no-console': off
  'import/extensions': [error, always]
  'arrow-parens': [error, as-needed]
  'comma-dangle': [error, always-multiline]
  'operator-linebreak': [error, after]
  'implicit-arrow-linebreak': [error, below]
  'eol-last': [error, always]
  'no-plusplus': off
  'no-trailing-spaces': error